=== YacineG03/WaxTaan/schema/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="user_id" type="xs:string"/>
                            <xs:element name="contact_name" type="xs:string"/>
                            <xs:element name="contact_phone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(77|70|78|76)[0-9]{7}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="contact_photo" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YacineG03/WaxTaan/xmls/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/contacts.xsd">
    <contact>
        <id>6871aa821a11e</id>
        <user_id>6871aa2634117</user_id>
        <contact_name>Yacine GUEYE</contact_name>
        <contact_phone>770123456</contact_phone>
    </contact>
    
<contact><id>6873f61d8d533</id><user_id>6871aa2634117</user_id><contact_name>Maarieee</contact_name><contact_phone>770123456</contact_phone></contact><contact><id>68741e5e87602</id><user_id>6871aa2634117</user_id><contact_name>Fatima</contact_name><contact_phone>770123456</contact_phone></contact><contact><id>6875627cd7069</id><user_id>6871a82975833</user_id><contact_name>Assyyyy</contact_name><contact_phone>770123456</contact_phone></contact><contact><id>6875743d9d082</id><user_id>6871a82975833</user_id><contact_name>Marie</contact_name><contact_phone>770123456</contact_phone></contact></contacts>
