=== YacineG03/WaxTaan/schema/waxtaan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Définition des utilisateurs -->
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="sex" type="xs:string" fixed="M" minOccurs="0"/>
                            <xs:element name="age" type="xs:positiveInteger"/>
                            <xs:element name="phone" type="xs:string">
                                <xs:pattern value="^(77|70|78|76)[0-9]{7}$"/>
                            </xs:element>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="profile_photo" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Définition des contacts -->
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="user_id" type="xs:string"/>
                            <xs:element name="contact_name" type="xs:string"/>
                            <xs:element name="contact_phone" type="xs:string">
                                <xs:pattern value="^(77|70|78|76)[0-9]{7}$"/>
                            </xs:element>
                            <xs:element name="contact_photo" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Définition des groupes -->
    <xs:element name="groups">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="group" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="admin_id" type="xs:string"/>
                            <xs:element name="coadmins" type="xs:string" minOccurs="0"/>
                            <xs:element name="group_photo" type="xs:string" minOccurs="0"/>
                            <xs:element name="member_id" type="xs:string" maxOccurs="unbounded" minOccurs="2"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Définition des messages -->
    <xs:element name="messages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="sender_id" type="xs:string"/>
                            <xs:element name="recipient" type="xs:string" minOccurs="0"/>
                            <xs:element name="recipient_group" type="xs:string" minOccurs="0"/>
                            <xs:element name="content" type="xs:string"/>
                            <xs:element name="file" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="timestamp" type="xs:dateTime" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== YacineG03/WaxTaan/xmls/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="waxtaan.xsd">
<message timestamp="2025-07-13 18:24:38"><id>6873ddc60e01b</id><sender_id>6871aa2634117</sender_id><content>coucouuu</content><recipient>777777777</recipient></message><message timestamp="2025-07-13 18:31:58"><id>6873df7e07412</id><sender_id>6871aa2634117</sender_id><content>Comment ca Va?</content><recipient>777777777</recipient></message><message timestamp="2025-07-13 19:01:25"><id>6873e665b4998</id><sender_id>6871aa2634117</sender_id><content>Et la journée&#13;
</content><recipient>777777777</recipient></message><message timestamp="2025-07-13 19:04:28"><id>6873e71cebe14</id><sender_id>6871aa2634117</sender_id><content>TOut va bein</content><recipient>777777777</recipient></message><message timestamp="2025-07-13 19:46:03"><id>6873f0db1f046</id><sender_id>6871a82975833</sender_id><content>Ca va et toi</content><recipient>778909890</recipient></message><message timestamp="2025-07-13 19:47:59"><id>6873f14fa2b47</id><sender_id>6871aa2634117</sender_id><content>Salut les filles</content><recipient_group>6871bf8db342d</recipient_group></message><message timestamp="2025-07-13 20:04:47"><id>6873f53f2b3fb</id><sender_id>6871aa2634117</sender_id><content>Ca va Alhamdoulilah&#13;
</content><recipient>777777777</recipient></message><message timestamp="2025-07-13 20:22:37"><id>6873f96dd77e8</id><sender_id>6871ae9cd9e8d</sender_id><content>Salut ca vaaa?</content><recipient_group>6871bf8db342d</recipient_group></message><message timestamp="2025-07-13 20:43:24"><id>6873fe4c866b3</id><sender_id>6871aa2634117</sender_id><content>hey</content><recipient>777777777</recipient><file>6873fe4c866e2_3.jfif</file></message><message timestamp="2025-07-13 20:44:55"><id>6873fea75a7af</id><sender_id>6871aa2634117</sender_id><content>nkvndkvn</content><recipient>777777777</recipient><file>6873fea75a7ce_2.png</file></message><message timestamp="2025-07-13 20:45:50"><id>6873fede597ec</id><sender_id>6871aa2634117</sender_id><content>fjheiodfheiln</content><recipient>777777777</recipient><file>6873fede59807_Capture d’écran 2024-10-10 172727.png</file></message><message timestamp="2025-07-13 20:49:26"><id>6873ffb6dbbb0</id><sender_id>6871aa2634117</sender_id><content/><recipient>777777777</recipient><file>6873ffb6dbbd5_1.png</file></message><message timestamp="2025-07-13 20:49:34"><id>6873ffbe09494</id><sender_id>6871aa2634117</sender_id><content/><recipient>777777777</recipient></message><message timestamp="2025-07-14 00:19:35"><id>687430f7a0578</id><sender_id>6871aa2634117</sender_id><content>Heeeeey&#13;
</content><recipient_group>68742d77d499e</recipient_group></message></messages>

=== YacineG03/WaxTaan/xmls/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="waxtaan.xsd">
<!-- <user><id>6871a82975833</id><name>Yacine GUEYE</name><phone>777777777</phone><password>$2y$10$b2PmMk70nQjcrQCY0qXopeaA3NqnDuAdWrxE2DMqT4mNnR/e7dfy6</password></user> -->
<!-- <user><id>6871aa2634117</id><firstname>Assy</firstname><lastname>NDIAYE</lastname><sex>F</sex><age>10</age><phone>778909890</phone><password>$2y$10$kJO8pmP1cftuX1mBi.YHB.j6S5uCqfx5KKWfBjrQUc0PLb.iEL./m</password><profile_photo>6871ba7449088_default.png</profile_photo></user><user><id>6871ae9cd9e8d</id><firstname>Mariama</firstname><lastname>DIOUM</lastname><sex>F</sex><age>0</age><phone>700000000</phone><password>$2y$10$ttWrHIp7uTaKVhvg82SZ.OI2umPls6InQAWGoT5wklePjCpk88OHy</password><profile_photo>default.jpg</profile_photo></user></users> -->
    <user>
            <id>6871a82975833</id>
            <firstname>Yacine</firstname>
            <lastname>GUEYE</lastname>
            <sex>M</sex>
            <age>20</age>
            <phone>777777777</phone>
            <password>$2y$10$b2PmMk70nQjcrQCY0qXopeaA3NqnDuAdWrxE2DMqT4mNnR/e7dfy6</password>
            <profile_photo>default.jpg</profile_photo>
        </user>
        <user>
            <id>6871aa2634117</id>
            <firstname>Assy</firstname>
            <lastname>NDIAYE</lastname>
            <sex>F</sex>
            <age>10</age>
            <phone>778909890</phone>
            <password>$2y$10$kJO8pmP1cftuX1mBi.YHB.j6S5uCqfx5KKWfBjrQUc0PLb.iEL./m</password>
            <profile_photo>6871ba7449088_default.png</profile_photo>
        </user>
        <user>
            <id>6871ae9cd9e8d</id>
            <firstname>Mariama</firstname>
            <lastname>DIOUM</lastname>
            <sex>F</sex>
            <age>0</age>
            <phone>700000000</phone>
            <password>$2y$10$ttWrHIp7uTaKVhvg82SZ.OI2umPls6InQAWGoT5wklePjCpk88OHy</password>
            <profile_photo>default.jpg</profile_photo>
        </user>
</users>
